# Generated by Django 2.0.3 on 2018-04-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
    ]
